# Site configuration
title: Serena Peruzzo
name:  Serena Peruzzo
author: Serena Peruzzo
work:  Data Scientist
year: 2019

# Navigation
nav1: "About"
nav2: "Work"
nav3: "Projects"

# Section1
# namesmall: "Serena Peruzzo"
tagline: "Data scientist. Recurse Center alumna. Travel junkie."
bio: "Serena is a senior data scientist at the analytics consultancy Bardess, currently based in Toronto, Canada. Before joining Bardess, she has worked both in academia as an ML researcher and in the industry as a data science consultant on the Australian, British and Canadian markets. Serena is passionate about education, community and tech for good and she splits her free time between mentoring data science students, organizing meetups and volunteering."

# Section 2

talks: [
  ["https://www.thestrangeloop.com/2019/improving-law-interpretability-using-nlp.html", "Improving law interpretability using NLP", "Strange Loop 2019 (upcoming)"],
  ["https://odsc.com/training/portfolio/analyzing-legislative-burden-upon-businesses-using-nlp-and-ml-2/", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "ODSC East 2019, Boston"],
  ["https://learnai.odsc.com/courses/odsc-east-2019-warm-up-open-source", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "ODSC East 2019 Warm-Up: Open Source"],
  ["https://www.youtube.com/watch?v=bmzck327cro", "Data Driven Literary Analysis", "PyData Amsterdam 2016"]
]

articles: [
  ["https://opendatascience.com/using-nlp-and-ml-to-analyze-legislative-burdens-upon-businesses/", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "Open Data Science blog, April 2019"],
  ["https://recompilermag.com/issues/issue-6/data-cleaning-a-necessary-chore/", "Data Cleaning a Necessary Chore", "The Recompiler, Issue Six - March 2017"],
  ["https://codewords.recurse.com/issues/seven/data-driven-literary-analysis", "Code Words, Issue Seven - October 2016", "Code Words, Issue Seven - October 2016"]
]

publications: [
  ["S. Peruzzo, M. Holenderski & J. J. Lukkien, Pattern-based feature extraction for fault detection in quality relevant process control, ETFA 2017"],
  ["C. Hull, E. Stark , S. Peruzzo & C. Sims, 2013, Avian collisions at two wind farms in Tasmania, Australia: Taxonomic and ecological characteristics of colliders versus non-colliders , New Zealand Journal of Zoology, 40:1, 47-62"]
]

# Section 3
sec6: "Projects"
sec7: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer non. Adipiscing cubilia elementum integer. Integer eu ante ornare amet commetus."
sec8: "Possibly broke spacetime"
sec9: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec10: "Terraformed a small moon"
sec11: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."
sec12: "Snapped dark matter in the wild"
sec13: "Integer eu ante ornare amet commetus vestibulum blandit integer in curae ac faucibus integer adipiscing ornare amet."

# Social Links
# facebook: username
twitter:  sereprz
#google: username
#instagram: username
#pinterest: username
#linkedin: username
#youtube: username
#spotify: username
#lastfm: username
github: sereprz
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: serena.peruzzo@gmail.com

