# Site configuration
title: Serena Peruzzo
name:  Serena Peruzzo
author: Serena Peruzzo
work: Currently based in Toronto
year: 2019


tagline: "Data scientist. Recurse Center alumna. Travel junkie."
bio: "Serena is a senior data scientist at the analytics consultancy Bardess, currently based in Toronto, Canada. Before joining Bardess, she has worked both in academia as an ML researcher and in the industry as a data science consultant on the Australian, British and Canadian markets. Serena is passionate about education, community and tech for good and she splits her free time between mentoring data science students, organizing meetups and volunteering."


# Speaking

talks: [
  ["https://www.youtube.com/watch?v=c-WTaLX4QzU", "Improving Law Interpretability Using NLP", "Strange Loop 2019"],
  ["https://odsc.com/training/portfolio/analyzing-legislative-burden-upon-businesses-using-nlp-and-ml-2/", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "ODSC East 2019, Boston"],
  ["https://learnai.odsc.com/courses/odsc-east-2019-warm-up-open-source", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "ODSC East 2019 Warm-Up: Open Source"],
  ["https://www.youtube.com/watch?v=bmzck327cro", "Data Driven Literary Analysis", "PyData Amsterdam 2016"]
]

# Writing

articles: [
  ["https://opendatascience.com/using-nlp-and-ml-to-analyze-legislative-burdens-upon-businesses/", "Using NLP and ML to Analyze Legislative Burdens Upon Businesses", "Open Data Science blog, April 2019"],
  ["http://www.bardess.com/what-factors-matter-in-data-science-success/", "What Factors Matter in Data Science Success?", "Bardess blog, May 2018"],
  ["https://recompilermag.com/issues/issue-6/data-cleaning-a-necessary-chore/", "Data Cleaning a Necessary Chore", "The Recompiler, Issue Six - March 2017"],
  ["https://codewords.recurse.com/issues/seven/data-driven-literary-analysis", "Code Words, Issue Seven - October 2016", "Code Words, Issue Seven - October 2016"]
]

# Research

publications: [
  ["S. Peruzzo, M. Holenderski & J. J. Lukkien, Pattern-based feature extraction for fault detection in quality relevant process control", "ETFA 2017", "/assets/docs/ETFA2017.pdf"],
  ["C. Hull, E. Stark , S. Peruzzo & C. Sims, 2013, Avian collisions at two wind farms in Tasmania, Australia: Taxonomic and ecological characteristics of colliders versus non-colliders", "New Zealand Journal of Zoology, 40:1, 47-62", "https://www.tandfonline.com/doi/full/10.1080/03014223.2012.757243"]
]

# Projects

proj1: "autosummary"
proj1-link: http://autosummary.serenaperuzzo.com/
proj1-image: /assets/images/autosummary.jpg
proj1-desc: "Document summarisation by keyphrase extraction: a simple algorithm for summarising the content of articles/web pages built in Flask"

proj2: "Shakespeare Classifier"
proj2-link: https://github.com/sereprz/ShakespeareTextAnalysis
proj2-image: /assets/images/shakespeare.jpg
proj2-desc: "Unsupervised document classification with LDA and KMeans in Python"

proj3: "RC Social Interactions"
proj3-link: http://rcsocial.serenaperuzzo.com/
proj3-image: /assets/images/rcsocial.jpg
proj3-desc: "A representation of social interactions at Recurse Center using D3"

proj4: "Baby Names Wizard"
proj4-link: https://github.com/sereprz/BabyNamesWizard
proj4-image: /assets/images/babynames.jpg
proj4-desc: "Name popularity in the US: a visual exploration of baby names in the US made in R using shiny and ggplot2"


# Social Links
# facebook: username
twitter:  sereprz
#google: username
#instagram: username
#pinterest: username
linkedin: speruzzo
#youtube: username
#spotify: username
#lastfm: username
github: sereprz
#stackoverflow: username
#quora: username
#reddit: username
#medium: username
#vimeo: username
#keybase: username
email: serena.peruzzo@gmail.com


theme: jekyll-theme-minimal
